plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()

	maven {
		name = 'Sponge / Mixin'
		url = 'https://repo.spongepowered.org/repository/maven-public/'
	}

	maven {
		name = 'BlameJared Maven (CrT / Bookshelf)'
		url = 'https://maven.blamejared.com'
	}

	maven {
		name = 'Roughly Enough Items'
		url = "https://maven.shedaniel.me"
	}

	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
}

loom {
	splitEnvironmentSourceSets()
	accessWidenerPath = file("src/main/resources/superflat-progression.accesswidener")

	mods {
		"superflat-progression" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs {
		client {
			client()
			configName = "Minecraft Client"
			programArgs "--username", "DevPlayer"
			runDir("run/client")
		}

		server {
			server()
			configName = "Minecraft Server"
			runDir("run/server")
		}

		clientNone {
			inherit client
			configName = "Minecraft Client (No Recipe Viewer)"
			programArgs "--username", "DevPlayer"
			runDir("run/client")
		}

		clientRei {
			inherit client
			configName = "Minecraft Client (REI)"
			programArgs "--username", "DevPlayer"
			runDir("run/client")
		}

		serverNone {
			inherit server
			configName = "Minecraft Server (No Recipe Viewer)"
			runDir("run/server")
		}

		serverRei {
			inherit server
			configName = "Minecraft Server (REI)"
			runDir("run/server")
		}
	}

	runConfigs.configureEach {
		ideConfigGenerated = true
	}
}

def requestedTasks = gradle.startParameter.taskNames*.toLowerCase(Locale.ROOT)

// Find the first run task and strip either runclient or runserver from the front
def taskViewer = requestedTasks
	.find { it.startsWith("runclient") || it.startsWith("runserver") }
	?.replaceFirst(/^run(client|server)/, "")

def projectViewer = project.findProperty("recipe_viewer")

def recipeViewer = (
	(taskViewer != null && !taskViewer.isBlank() ? taskViewer : null)
	?: projectViewer
	?: ""
).toString().toLowerCase(Locale.ROOT)

println "Using recipeViewer = ${recipeViewer}"

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}+${project.minecraft_version}"

	// Architectury and Cloth Config
	modApi("dev.architectury:architectury-fabric:${architectury_version}")
	modApi("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}

	// REI (Roughly Enough Items)
	modCompileOnly("me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}
	modCompileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${rei_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}

	// Which recipe viewer to use at runtime.
	switch (recipeViewer) {
		case "rei":
			modLocalRuntime("me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}") {
				exclude group: "net.fabricmc.fabric-api"
			}
			break

		case "disabled":
		case "none":
		case "":
			break

		default:
			println("Unknown recipe viewer specified: ${recipeViewer}. Must be rei, or none.")
			break
	}

	// Jade
	modCompileOnly("maven.modrinth:jade:${jade_version}+fabric") {
		exclude(group: "net.fabricmc.fabric-api")
	}
	modLocalRuntime("maven.modrinth:jade:${jade_version}+fabric") {
		exclude(group: "net.fabricmc.fabric-api")
	}
}

processResources {
	var replaceProperties = [
			version					: project.version,
			java_version			: project.java_version,
			minecraft_version		: project.minecraft_version,
			loader_version			: project.loader_version,
			fabric_api_version		: project.fabric_api_version,
			rei_version				: project.rei_version
	]

	inputs.properties replaceProperties

	filesMatching("fabric.mod.json") {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

tasks.withType(JavaCompile) {
	options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}
